### ISSUE TITLE
Display surah.ayah in arabic

### ISSUE THREAD

**Issue by arycloud** [Keda87/python-quran-odoa#1]
How can we display the `surah.ayah` in arabic?

**Comment by Keda87** [comment]
Hi @arycloud 

`surah.ayah` is already returned a quran arabic, but if you are on python 3 you have to decode it because python 3 returned a byte `surah.ayah.decode() / surah.ayah.decode('utf8')`

**Comment by Keda87** [comment]
I closed this issue due to inactive discussion
